Feature/cw 14 signup
luisrca-tech/Attios-CRM pull request #11
Opened 2024-10-24 17:18 UTC by luisrca-tech

2024-11-02 22:26 UTC, mateusmenesesDev commented on package.json
> +    "@clerk/testing": "^1.3.16",
Não vamos precisar do ngrok?

2024-11-02 22:31 UTC, mateusmenesesDev commented on src/common/components/ui/Icons/index.tsx
> +  Google: GoogleIcon,
Que tal termos um nested para as redes sociais? Igual foi feito para o Arrow
Entraria Google, Facebook, Twitter

2024-11-02 22:32 UTC, mateusmenesesDev commented on src/common/components/ui/Spinner.tsx
> +  return <div className="h-4 w-4 animate-spin rounded-full border-b-2 border-t-2 border-white-100"></div>;
Faz a div fechar nela mesma

2024-11-02 22:32 UTC, mateusmenesesDev commented on src/common/components/ui/Spinner.tsx
> +  return <div className="h-4 w-4 animate-spin rounded-full border-b-2 border-t-2 border-white-100"></div>;
Adiciona o role loading (eu acho que é assim)

2024-11-02 22:33 UTC, mateusmenesesDev commented on src/common/hooks/use-toast.ts
> +import type { ToastActionElement, ToastProps } from "~/common/components/ui/toast";
Isso ainda é necessário? Acredito que mudamos para o toast do sonner

2024-11-02 23:23 UTC, mateusmenesesDev requested changes

2024-11-02 23:23 UTC, mateusmenesesDev commented on src/features/auth/components/ExternalAccounts.tsx
> +      <Button variant="outlined" color="secondary">
Esses botões ainda não estão fazendo nada?

2024-11-02 23:23 UTC, mateusmenesesDev commented on src/features/auth/components/ExternalAccounts.tsx
> +export function ExternalAccounts() {
Podemos modificar para SocialAuth?

2024-11-02 23:23 UTC, mateusmenesesDev commented on src/server/db/schema.ts
>  		createdAt: timestamp('created_at', { withTimezone: true })
Esta faltando um updatedAt

2024-11-02 23:23 UTC, mateusmenesesDev commented on src/server/db/schema.ts
>  	(example) => ({
example é o melhor nome para esse params?

2024-11-02 23:30 UTC, luisrca-tech commented on package.json
> +    "@clerk/testing": "^1.3.16",
O ngrok vai entrar na parte de autenticação pelas redes sociais? certo!?

2024-11-02 23:31 UTC, luisrca-tech commented on src/common/components/ui/Spinner.tsx
> +  return <div className="h-4 w-4 animate-spin rounded-full border-b-2 border-t-2 border-white-100"></div>;
é um estilo??

2024-11-02 23:31 UTC, luisrca-tech commented on src/features/auth/components/ExternalAccounts.tsx
> +export function ExternalAccounts() {
Sim!

2024-11-03 00:57 UTC, mateusmenesesDev commented on src/common/components/ui/Spinner.tsx
> +  return <div className="h-4 w-4 animate-spin rounded-full border-b-2 border-t-2 border-white-100"></div>;
Não, é uma prop relacionada a acessibilidade

2024-11-03 00:57 UTC, mateusmenesesDev commented on package.json
> +    "@clerk/testing": "^1.3.16",
Certo. Nós temos as redes sociais separadas dessa task?

2024-11-03 01:05 UTC, luisrca-tech commented on package.json
> +    "@clerk/testing": "^1.3.16",
Não temo, também pensei nessa possibilidade, só não comentei com você. Acho bom né?!

2024-11-04 20:02 UTC, mateusmenesesDev requested changes

2024-11-04 22:18 UTC, mateusmenesesDev approved these changes

2024-11-04 22:18 UTC, merged