Feature/cw 28 input component
luisrca-tech/Attios-CRM pull request #8
Opened 2024-10-18 19:32 UTC by luisrca-tech

2024-10-18 19:44 UTC, mateusmenesesDev commented on src/components/ui/Input/InputText.tsx
> +      {iconLeft && <Image className="absolute top-2" src={iconLeft} alt="" />}
Coloca esse icon no InputRoot

2024-10-19 14:07 UTC, luisrca-tech commented on src/components/ui/Input/InputText.tsx
> +      {iconLeft && <Image className="absolute top-2" src={iconLeft} alt="" />}
Dessa forma a gente entra em um problema em centalizar esses icons dentro do input... pq no wrapper ele acaba podendo ficar no componente todo, fica mais dificil de alocar ele corretamente em erros possiveis, finalizei todos, acredito que ficou bom, da uma olhada pfvr.

2024-10-22 13:24 UTC, mateusmenesesDev requested changes

2024-10-22 13:24 UTC, mateusmenesesDev commented on src/app/page.tsx
> +            iconLeft={<Icon.User />}
No input acima temos InputIcon.Error, aqui temos Icon.User
Vamos pensar se realmente precisamos ter dois diferentes, ou se apenas um Icon.[Element] genérico é suficiente.

Se caso realmente seja necessário utilizar dois diferentes, aqui deveríamos estar utilizando o Icon? Não deveria ser o InputIcon? (Entendo que você colocou como Mock, mas só para interpretar a necessidade dois, estou questionando isso.)

2024-10-22 13:24 UTC, mateusmenesesDev commented on src/components/Icons/Arrow/ArrowDown.tsx
> +interface ArrowDown {
Invés de criar uma interface para cada icon. Cria uma genérica que valerá para todos os icons
IconProps.

2024-10-22 13:24 UTC, mateusmenesesDev commented on src/components/Icons/Input/ErrorIcon.tsx
Segundo o que tivemos na mentoria de ontem, vamos modificar as pastas.

src/common/ui/icons

2024-10-22 13:24 UTC, mateusmenesesDev commented on src/components/ui/Input/InputRoot.tsx
> +      <div
Não entendi essa div vazia

2024-10-22 13:24 UTC, mateusmenesesDev commented on src/components/ui/Input/SelectInput.tsx
> +    const handleClickOutside = (event: MouseEvent) => {
Cria um custom hook para isso porque podemos reutilizar em muitas coisas do projeto

useClickOutside

2024-10-23 13:08 UTC, luisrca-tech commented on src/components/ui/Input/InputRoot.tsx
> +      <div
Essa div vazia é a borda embaixo dos inputs, ai ela vai receber o erro ou success do form pra mudar a cor

2024-10-23 22:06 UTC, mateusmenesesDev commented on src/common/ui/Input/InputText.tsx
> +          "h-full w-full border-none font-bold text-black text-sm leading-5 outline-none placeholder:text-primary-200",
Percebi que tiramos o outline e border
Mesmo que o figma siga esse padrão, vamos deixar a borda ao input ser selecionado.

É uma pessima experiência de usuário se o usuário clicar em algo e não tiver um feedback do que ele clicou foi realmente selecionado

2024-10-24 11:42 UTC, mateusmenesesDev approved these changes

2024-10-24 11:42 UTC, merged